2023-11-04 16:14:17,970:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-04 16:14:17,970:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-04 16:14:17,970:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-04 16:14:17,970:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-04 16:14:19,865:INFO:PyCaret ClassificationExperiment
2023-11-04 16:14:19,865:INFO:Logging name: clf-default-name
2023-11-04 16:14:19,865:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-04 16:14:19,865:INFO:version 3.1.0
2023-11-04 16:14:19,865:INFO:Initializing setup()
2023-11-04 16:14:19,865:INFO:self.USI: 4115
2023-11-04 16:14:19,865:INFO:self._variable_keys: {'_ml_usecase', 'log_plots_param', 'is_multiclass', 'logging_param', 'fold_shuffle_param', 'gpu_n_jobs_param', 'target_param', 'X', 'X_test', 'memory', 'html_param', 'fold_groups_param', 'USI', 'exp_name_log', 'pipeline', 'data', 'fold_generator', 'seed', 'y_train', 'exp_id', 'X_train', 'fix_imbalance', 'idx', 'y_test', 'gpu_param', 'y', 'n_jobs_param', '_available_plots'}
2023-11-04 16:14:19,865:INFO:Checking environment
2023-11-04 16:14:19,865:INFO:python_version: 3.10.11
2023-11-04 16:14:19,866:INFO:python_build: ('tags/v3.10.11:7d4cc5a', 'Apr  5 2023 00:38:17')
2023-11-04 16:14:19,866:INFO:machine: AMD64
2023-11-04 16:14:19,866:INFO:platform: Windows-10-10.0.22621-SP0
2023-11-04 16:14:19,866:INFO:Memory: svmem(total=16542101504, available=3809775616, percent=77.0, used=12732325888, free=3809775616)
2023-11-04 16:14:19,866:INFO:Physical Core: 6
2023-11-04 16:14:19,866:INFO:Logical Core: 12
2023-11-04 16:14:19,866:INFO:Checking libraries
2023-11-04 16:14:19,866:INFO:System:
2023-11-04 16:14:19,866:INFO:    python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
2023-11-04 16:14:19,866:INFO:executable: C:\Users\Hannah Cimene\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
2023-11-04 16:14:19,866:INFO:   machine: Windows-10-10.0.22621-SP0
2023-11-04 16:14:19,866:INFO:PyCaret required dependencies:
2023-11-04 16:14:19,882:INFO:                 pip: 23.0.1
2023-11-04 16:14:19,882:INFO:          setuptools: 65.5.0
2023-11-04 16:14:19,882:INFO:             pycaret: 3.1.0
2023-11-04 16:14:19,882:INFO:             IPython: 8.15.0
2023-11-04 16:14:19,882:INFO:          ipywidgets: 8.1.1
2023-11-04 16:14:19,882:INFO:                tqdm: 4.64.1
2023-11-04 16:14:19,882:INFO:               numpy: 1.23.5
2023-11-04 16:14:19,882:INFO:              pandas: 1.5.2
2023-11-04 16:14:19,882:INFO:              jinja2: 3.1.2
2023-11-04 16:14:19,882:INFO:               scipy: 1.10.1
2023-11-04 16:14:19,882:INFO:              joblib: 1.2.0
2023-11-04 16:14:19,883:INFO:             sklearn: 1.2.2
2023-11-04 16:14:19,883:INFO:                pyod: 1.1.0
2023-11-04 16:14:19,883:INFO:            imblearn: 0.11.0
2023-11-04 16:14:19,883:INFO:   category_encoders: 2.6.2
2023-11-04 16:14:19,883:INFO:            lightgbm: 4.1.0
2023-11-04 16:14:19,883:INFO:               numba: 0.58.0
2023-11-04 16:14:19,883:INFO:            requests: 2.28.1
2023-11-04 16:14:19,883:INFO:          matplotlib: 3.6.3
2023-11-04 16:14:19,883:INFO:          scikitplot: 0.3.7
2023-11-04 16:14:19,883:INFO:         yellowbrick: 1.5
2023-11-04 16:14:19,883:INFO:              plotly: 5.17.0
2023-11-04 16:14:19,883:INFO:    plotly-resampler: Not installed
2023-11-04 16:14:19,883:INFO:             kaleido: 0.2.1
2023-11-04 16:14:19,883:INFO:           schemdraw: 0.15
2023-11-04 16:14:19,883:INFO:         statsmodels: 0.13.5
2023-11-04 16:14:19,883:INFO:              sktime: 0.21.1
2023-11-04 16:14:19,883:INFO:               tbats: 1.1.3
2023-11-04 16:14:19,883:INFO:            pmdarima: 2.0.3
2023-11-04 16:14:19,883:INFO:              psutil: 5.9.3
2023-11-04 16:14:19,883:INFO:          markupsafe: 2.1.1
2023-11-04 16:14:19,883:INFO:             pickle5: Not installed
2023-11-04 16:14:19,883:INFO:         cloudpickle: 2.2.1
2023-11-04 16:14:19,883:INFO:         deprecation: 2.1.0
2023-11-04 16:14:19,883:INFO:              xxhash: 3.3.0
2023-11-04 16:14:19,883:INFO:           wurlitzer: Not installed
2023-11-04 16:14:19,883:INFO:PyCaret optional dependencies:
2023-11-04 16:14:21,416:INFO:                shap: Not installed
2023-11-04 16:14:21,417:INFO:           interpret: Not installed
2023-11-04 16:14:21,417:INFO:                umap: Not installed
2023-11-04 16:14:21,417:INFO:     ydata_profiling: Not installed
2023-11-04 16:14:21,417:INFO:  explainerdashboard: Not installed
2023-11-04 16:14:21,417:INFO:             autoviz: Not installed
2023-11-04 16:14:21,417:INFO:           fairlearn: Not installed
2023-11-04 16:14:21,417:INFO:          deepchecks: Not installed
2023-11-04 16:14:21,417:INFO:             xgboost: Not installed
2023-11-04 16:14:21,417:INFO:            catboost: Not installed
2023-11-04 16:14:21,417:INFO:              kmodes: Not installed
2023-11-04 16:14:21,417:INFO:             mlxtend: Not installed
2023-11-04 16:14:21,417:INFO:       statsforecast: Not installed
2023-11-04 16:14:21,417:INFO:        tune_sklearn: Not installed
2023-11-04 16:14:21,417:INFO:                 ray: Not installed
2023-11-04 16:14:21,417:INFO:            hyperopt: Not installed
2023-11-04 16:14:21,417:INFO:              optuna: Not installed
2023-11-04 16:14:21,417:INFO:               skopt: Not installed
2023-11-04 16:14:21,417:INFO:              mlflow: Not installed
2023-11-04 16:14:21,417:INFO:              gradio: Not installed
2023-11-04 16:14:21,417:INFO:             fastapi: 0.87.0
2023-11-04 16:14:21,417:INFO:             uvicorn: 0.20.0
2023-11-04 16:14:21,417:INFO:              m2cgen: Not installed
2023-11-04 16:14:21,417:INFO:           evidently: Not installed
2023-11-04 16:14:21,417:INFO:               fugue: Not installed
2023-11-04 16:14:21,417:INFO:           streamlit: Not installed
2023-11-04 16:14:21,417:INFO:             prophet: Not installed
2023-11-04 16:14:21,417:INFO:None
2023-11-04 16:14:21,417:INFO:Set up data.
2023-11-04 16:14:21,421:INFO:Set up folding strategy.
2023-11-04 16:14:21,421:INFO:Set up train/test split.
2023-11-04 16:14:21,425:INFO:Set up index.
2023-11-04 16:14:21,425:INFO:Assigning column types.
2023-11-04 16:14:21,427:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-04 16:14:21,466:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-04 16:14:21,467:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:14:21,517:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,518:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,555:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-04 16:14:21,556:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:14:21,579:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,579:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,579:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-04 16:14:21,617:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:14:21,641:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,641:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,679:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:14:21,702:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,703:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,703:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-04 16:14:21,764:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,765:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,826:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,827:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,828:INFO:Preparing preprocessing pipeline...
2023-11-04 16:14:21,829:INFO:Set up simple imputation.
2023-11-04 16:14:21,830:INFO:Set up column name cleaning.
2023-11-04 16:14:21,846:INFO:Finished creating preprocessing pipeline.
2023-11-04 16:14:21,856:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\HANNAH~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['sex', 'alone',
                                             'Siblings/spouses aboard',
                                             'Parents/children aboard',
                                             'Passenger fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              st...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-11-04 16:14:21,856:INFO:Creating final display dataframe.
2023-11-04 16:14:21,911:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target          Survived
2                   Target type            Binary
3           Original data shape         (1309, 6)
4        Transformed data shape         (1309, 6)
5   Transformed train set shape          (916, 6)
6    Transformed test set shape          (393, 6)
7              Numeric features                 5
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              4115
2023-11-04 16:14:21,978:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:21,978:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:22,040:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:22,040:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:14:22,041:INFO:setup() successfully completed in 2.18s...............
2023-11-04 16:14:22,041:INFO:Initializing compare_models()
2023-11-04 16:14:22,041:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-04 16:14:22,041:INFO:Checking exceptions
2023-11-04 16:14:22,043:INFO:Preparing display monitor
2023-11-04 16:14:22,068:INFO:Initializing Logistic Regression
2023-11-04 16:14:22,068:INFO:Total runtime is 0.0 minutes
2023-11-04 16:14:22,072:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:22,072:INFO:Initializing create_model()
2023-11-04 16:14:22,072:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:22,072:INFO:Checking exceptions
2023-11-04 16:14:22,072:INFO:Importing libraries
2023-11-04 16:14:22,072:INFO:Copying training dataset
2023-11-04 16:14:22,075:INFO:Defining folds
2023-11-04 16:14:22,075:INFO:Declaring metric variables
2023-11-04 16:14:22,078:INFO:Importing untrained model
2023-11-04 16:14:22,081:INFO:Logistic Regression Imported successfully
2023-11-04 16:14:22,087:INFO:Starting cross validation
2023-11-04 16:14:22,087:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:26,636:INFO:Calculating mean and std
2023-11-04 16:14:26,640:INFO:Creating metrics dataframe
2023-11-04 16:14:26,645:INFO:Uploading results into container
2023-11-04 16:14:26,646:INFO:Uploading model into container now
2023-11-04 16:14:26,647:INFO:_master_model_container: 1
2023-11-04 16:14:26,647:INFO:_display_container: 2
2023-11-04 16:14:26,647:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-11-04 16:14:26,647:INFO:create_model() successfully completed......................................
2023-11-04 16:14:26,785:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:26,785:INFO:Creating metrics dataframe
2023-11-04 16:14:26,792:INFO:Initializing K Neighbors Classifier
2023-11-04 16:14:26,792:INFO:Total runtime is 0.07872616052627564 minutes
2023-11-04 16:14:26,795:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:26,795:INFO:Initializing create_model()
2023-11-04 16:14:26,795:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:26,795:INFO:Checking exceptions
2023-11-04 16:14:26,795:INFO:Importing libraries
2023-11-04 16:14:26,795:INFO:Copying training dataset
2023-11-04 16:14:26,800:INFO:Defining folds
2023-11-04 16:14:26,800:INFO:Declaring metric variables
2023-11-04 16:14:26,802:INFO:Importing untrained model
2023-11-04 16:14:26,805:INFO:K Neighbors Classifier Imported successfully
2023-11-04 16:14:26,811:INFO:Starting cross validation
2023-11-04 16:14:26,812:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:28,146:INFO:Calculating mean and std
2023-11-04 16:14:28,148:INFO:Creating metrics dataframe
2023-11-04 16:14:28,151:INFO:Uploading results into container
2023-11-04 16:14:28,151:INFO:Uploading model into container now
2023-11-04 16:14:28,152:INFO:_master_model_container: 2
2023-11-04 16:14:28,152:INFO:_display_container: 2
2023-11-04 16:14:28,152:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-11-04 16:14:28,152:INFO:create_model() successfully completed......................................
2023-11-04 16:14:28,261:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:28,261:INFO:Creating metrics dataframe
2023-11-04 16:14:28,268:INFO:Initializing Naive Bayes
2023-11-04 16:14:28,268:INFO:Total runtime is 0.10333005587259929 minutes
2023-11-04 16:14:28,272:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:28,272:INFO:Initializing create_model()
2023-11-04 16:14:28,272:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:28,272:INFO:Checking exceptions
2023-11-04 16:14:28,273:INFO:Importing libraries
2023-11-04 16:14:28,273:INFO:Copying training dataset
2023-11-04 16:14:28,277:INFO:Defining folds
2023-11-04 16:14:28,277:INFO:Declaring metric variables
2023-11-04 16:14:28,280:INFO:Importing untrained model
2023-11-04 16:14:28,283:INFO:Naive Bayes Imported successfully
2023-11-04 16:14:28,289:INFO:Starting cross validation
2023-11-04 16:14:28,290:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:28,335:INFO:Calculating mean and std
2023-11-04 16:14:28,335:INFO:Creating metrics dataframe
2023-11-04 16:14:28,337:INFO:Uploading results into container
2023-11-04 16:14:28,338:INFO:Uploading model into container now
2023-11-04 16:14:28,338:INFO:_master_model_container: 3
2023-11-04 16:14:28,338:INFO:_display_container: 2
2023-11-04 16:14:28,338:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-04 16:14:28,338:INFO:create_model() successfully completed......................................
2023-11-04 16:14:28,437:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:28,437:INFO:Creating metrics dataframe
2023-11-04 16:14:28,445:INFO:Initializing Decision Tree Classifier
2023-11-04 16:14:28,445:INFO:Total runtime is 0.10627350409825644 minutes
2023-11-04 16:14:28,449:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:28,449:INFO:Initializing create_model()
2023-11-04 16:14:28,449:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:28,449:INFO:Checking exceptions
2023-11-04 16:14:28,449:INFO:Importing libraries
2023-11-04 16:14:28,449:INFO:Copying training dataset
2023-11-04 16:14:28,453:INFO:Defining folds
2023-11-04 16:14:28,453:INFO:Declaring metric variables
2023-11-04 16:14:28,456:INFO:Importing untrained model
2023-11-04 16:14:28,461:INFO:Decision Tree Classifier Imported successfully
2023-11-04 16:14:28,467:INFO:Starting cross validation
2023-11-04 16:14:28,468:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:28,513:INFO:Calculating mean and std
2023-11-04 16:14:28,513:INFO:Creating metrics dataframe
2023-11-04 16:14:28,516:INFO:Uploading results into container
2023-11-04 16:14:28,517:INFO:Uploading model into container now
2023-11-04 16:14:28,517:INFO:_master_model_container: 4
2023-11-04 16:14:28,517:INFO:_display_container: 2
2023-11-04 16:14:28,517:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-04 16:14:28,517:INFO:create_model() successfully completed......................................
2023-11-04 16:14:28,612:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:28,612:INFO:Creating metrics dataframe
2023-11-04 16:14:28,620:INFO:Initializing SVM - Linear Kernel
2023-11-04 16:14:28,620:INFO:Total runtime is 0.10919535954793295 minutes
2023-11-04 16:14:28,623:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:28,624:INFO:Initializing create_model()
2023-11-04 16:14:28,624:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:28,624:INFO:Checking exceptions
2023-11-04 16:14:28,624:INFO:Importing libraries
2023-11-04 16:14:28,624:INFO:Copying training dataset
2023-11-04 16:14:28,628:INFO:Defining folds
2023-11-04 16:14:28,628:INFO:Declaring metric variables
2023-11-04 16:14:28,630:INFO:Importing untrained model
2023-11-04 16:14:28,633:INFO:SVM - Linear Kernel Imported successfully
2023-11-04 16:14:28,639:INFO:Starting cross validation
2023-11-04 16:14:28,640:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:28,669:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,669:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,670:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,672:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,673:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,673:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,675:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:28,677:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,678:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:28,679:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,680:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,681:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:14:28,689:INFO:Calculating mean and std
2023-11-04 16:14:28,689:INFO:Creating metrics dataframe
2023-11-04 16:14:28,692:INFO:Uploading results into container
2023-11-04 16:14:28,692:INFO:Uploading model into container now
2023-11-04 16:14:28,692:INFO:_master_model_container: 5
2023-11-04 16:14:28,692:INFO:_display_container: 2
2023-11-04 16:14:28,692:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-04 16:14:28,692:INFO:create_model() successfully completed......................................
2023-11-04 16:14:28,789:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:28,789:INFO:Creating metrics dataframe
2023-11-04 16:14:28,796:INFO:Initializing Ridge Classifier
2023-11-04 16:14:28,797:INFO:Total runtime is 0.11214985450108847 minutes
2023-11-04 16:14:28,800:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:28,800:INFO:Initializing create_model()
2023-11-04 16:14:28,800:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:28,800:INFO:Checking exceptions
2023-11-04 16:14:28,800:INFO:Importing libraries
2023-11-04 16:14:28,800:INFO:Copying training dataset
2023-11-04 16:14:28,804:INFO:Defining folds
2023-11-04 16:14:28,804:INFO:Declaring metric variables
2023-11-04 16:14:28,807:INFO:Importing untrained model
2023-11-04 16:14:28,810:INFO:Ridge Classifier Imported successfully
2023-11-04 16:14:28,816:INFO:Starting cross validation
2023-11-04 16:14:28,817:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:28,846:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,847:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,849:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,850:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,850:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,850:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,852:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,853:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,853:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,855:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:14:28,863:INFO:Calculating mean and std
2023-11-04 16:14:28,863:INFO:Creating metrics dataframe
2023-11-04 16:14:28,866:INFO:Uploading results into container
2023-11-04 16:14:28,866:INFO:Uploading model into container now
2023-11-04 16:14:28,866:INFO:_master_model_container: 6
2023-11-04 16:14:28,866:INFO:_display_container: 2
2023-11-04 16:14:28,867:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-04 16:14:28,867:INFO:create_model() successfully completed......................................
2023-11-04 16:14:28,962:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:28,962:INFO:Creating metrics dataframe
2023-11-04 16:14:28,970:INFO:Initializing Random Forest Classifier
2023-11-04 16:14:28,970:INFO:Total runtime is 0.11502763827641806 minutes
2023-11-04 16:14:28,973:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:28,974:INFO:Initializing create_model()
2023-11-04 16:14:28,974:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:28,974:INFO:Checking exceptions
2023-11-04 16:14:28,974:INFO:Importing libraries
2023-11-04 16:14:28,974:INFO:Copying training dataset
2023-11-04 16:14:28,978:INFO:Defining folds
2023-11-04 16:14:28,978:INFO:Declaring metric variables
2023-11-04 16:14:28,982:INFO:Importing untrained model
2023-11-04 16:14:28,988:INFO:Random Forest Classifier Imported successfully
2023-11-04 16:14:28,992:INFO:Starting cross validation
2023-11-04 16:14:28,994:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:29,358:INFO:Calculating mean and std
2023-11-04 16:14:29,358:INFO:Creating metrics dataframe
2023-11-04 16:14:29,363:INFO:Uploading results into container
2023-11-04 16:14:29,363:INFO:Uploading model into container now
2023-11-04 16:14:29,364:INFO:_master_model_container: 7
2023-11-04 16:14:29,364:INFO:_display_container: 2
2023-11-04 16:14:29,364:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-11-04 16:14:29,364:INFO:create_model() successfully completed......................................
2023-11-04 16:14:29,468:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:29,468:INFO:Creating metrics dataframe
2023-11-04 16:14:29,479:INFO:Initializing Quadratic Discriminant Analysis
2023-11-04 16:14:29,479:INFO:Total runtime is 0.12350536584854127 minutes
2023-11-04 16:14:29,482:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:29,482:INFO:Initializing create_model()
2023-11-04 16:14:29,482:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:29,482:INFO:Checking exceptions
2023-11-04 16:14:29,483:INFO:Importing libraries
2023-11-04 16:14:29,483:INFO:Copying training dataset
2023-11-04 16:14:29,485:INFO:Defining folds
2023-11-04 16:14:29,486:INFO:Declaring metric variables
2023-11-04 16:14:29,488:INFO:Importing untrained model
2023-11-04 16:14:29,490:INFO:Quadratic Discriminant Analysis Imported successfully
2023-11-04 16:14:29,498:INFO:Starting cross validation
2023-11-04 16:14:29,499:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:29,548:INFO:Calculating mean and std
2023-11-04 16:14:29,548:INFO:Creating metrics dataframe
2023-11-04 16:14:29,552:INFO:Uploading results into container
2023-11-04 16:14:29,552:INFO:Uploading model into container now
2023-11-04 16:14:29,552:INFO:_master_model_container: 8
2023-11-04 16:14:29,552:INFO:_display_container: 2
2023-11-04 16:14:29,552:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-11-04 16:14:29,552:INFO:create_model() successfully completed......................................
2023-11-04 16:14:29,657:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:29,657:INFO:Creating metrics dataframe
2023-11-04 16:14:29,665:INFO:Initializing Ada Boost Classifier
2023-11-04 16:14:29,665:INFO:Total runtime is 0.12661725680033367 minutes
2023-11-04 16:14:29,669:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:29,669:INFO:Initializing create_model()
2023-11-04 16:14:29,669:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:29,669:INFO:Checking exceptions
2023-11-04 16:14:29,669:INFO:Importing libraries
2023-11-04 16:14:29,669:INFO:Copying training dataset
2023-11-04 16:14:29,673:INFO:Defining folds
2023-11-04 16:14:29,673:INFO:Declaring metric variables
2023-11-04 16:14:29,677:INFO:Importing untrained model
2023-11-04 16:14:29,680:INFO:Ada Boost Classifier Imported successfully
2023-11-04 16:14:29,686:INFO:Starting cross validation
2023-11-04 16:14:29,687:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:29,871:INFO:Calculating mean and std
2023-11-04 16:14:29,873:INFO:Creating metrics dataframe
2023-11-04 16:14:29,876:INFO:Uploading results into container
2023-11-04 16:14:29,876:INFO:Uploading model into container now
2023-11-04 16:14:29,877:INFO:_master_model_container: 9
2023-11-04 16:14:29,877:INFO:_display_container: 2
2023-11-04 16:14:29,877:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-11-04 16:14:29,877:INFO:create_model() successfully completed......................................
2023-11-04 16:14:29,972:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:29,972:INFO:Creating metrics dataframe
2023-11-04 16:14:29,983:INFO:Initializing Gradient Boosting Classifier
2023-11-04 16:14:29,983:INFO:Total runtime is 0.1319069266319275 minutes
2023-11-04 16:14:29,986:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:29,986:INFO:Initializing create_model()
2023-11-04 16:14:29,986:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:29,986:INFO:Checking exceptions
2023-11-04 16:14:29,986:INFO:Importing libraries
2023-11-04 16:14:29,986:INFO:Copying training dataset
2023-11-04 16:14:29,991:INFO:Defining folds
2023-11-04 16:14:29,991:INFO:Declaring metric variables
2023-11-04 16:14:29,994:INFO:Importing untrained model
2023-11-04 16:14:29,997:INFO:Gradient Boosting Classifier Imported successfully
2023-11-04 16:14:30,002:INFO:Starting cross validation
2023-11-04 16:14:30,004:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:30,172:INFO:Calculating mean and std
2023-11-04 16:14:30,173:INFO:Creating metrics dataframe
2023-11-04 16:14:30,177:INFO:Uploading results into container
2023-11-04 16:14:30,177:INFO:Uploading model into container now
2023-11-04 16:14:30,178:INFO:_master_model_container: 10
2023-11-04 16:14:30,178:INFO:_display_container: 2
2023-11-04 16:14:30,178:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-11-04 16:14:30,178:INFO:create_model() successfully completed......................................
2023-11-04 16:14:30,280:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:30,280:INFO:Creating metrics dataframe
2023-11-04 16:14:30,291:INFO:Initializing Linear Discriminant Analysis
2023-11-04 16:14:30,291:INFO:Total runtime is 0.13703583081563314 minutes
2023-11-04 16:14:30,293:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:30,293:INFO:Initializing create_model()
2023-11-04 16:14:30,293:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:30,293:INFO:Checking exceptions
2023-11-04 16:14:30,295:INFO:Importing libraries
2023-11-04 16:14:30,295:INFO:Copying training dataset
2023-11-04 16:14:30,298:INFO:Defining folds
2023-11-04 16:14:30,298:INFO:Declaring metric variables
2023-11-04 16:14:30,302:INFO:Importing untrained model
2023-11-04 16:14:30,304:INFO:Linear Discriminant Analysis Imported successfully
2023-11-04 16:14:30,311:INFO:Starting cross validation
2023-11-04 16:14:30,311:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:30,358:INFO:Calculating mean and std
2023-11-04 16:14:30,359:INFO:Creating metrics dataframe
2023-11-04 16:14:30,361:INFO:Uploading results into container
2023-11-04 16:14:30,361:INFO:Uploading model into container now
2023-11-04 16:14:30,362:INFO:_master_model_container: 11
2023-11-04 16:14:30,362:INFO:_display_container: 2
2023-11-04 16:14:30,362:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-11-04 16:14:30,362:INFO:create_model() successfully completed......................................
2023-11-04 16:14:30,459:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:30,459:INFO:Creating metrics dataframe
2023-11-04 16:14:30,468:INFO:Initializing Extra Trees Classifier
2023-11-04 16:14:30,468:INFO:Total runtime is 0.13999410072962443 minutes
2023-11-04 16:14:30,471:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:30,471:INFO:Initializing create_model()
2023-11-04 16:14:30,471:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:30,472:INFO:Checking exceptions
2023-11-04 16:14:30,472:INFO:Importing libraries
2023-11-04 16:14:30,472:INFO:Copying training dataset
2023-11-04 16:14:30,476:INFO:Defining folds
2023-11-04 16:14:30,476:INFO:Declaring metric variables
2023-11-04 16:14:30,479:INFO:Importing untrained model
2023-11-04 16:14:30,483:INFO:Extra Trees Classifier Imported successfully
2023-11-04 16:14:30,488:INFO:Starting cross validation
2023-11-04 16:14:30,488:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:30,791:INFO:Calculating mean and std
2023-11-04 16:14:30,793:INFO:Creating metrics dataframe
2023-11-04 16:14:30,796:INFO:Uploading results into container
2023-11-04 16:14:30,796:INFO:Uploading model into container now
2023-11-04 16:14:30,797:INFO:_master_model_container: 12
2023-11-04 16:14:30,797:INFO:_display_container: 2
2023-11-04 16:14:30,797:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-11-04 16:14:30,797:INFO:create_model() successfully completed......................................
2023-11-04 16:14:30,894:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:30,894:INFO:Creating metrics dataframe
2023-11-04 16:14:30,904:INFO:Initializing Light Gradient Boosting Machine
2023-11-04 16:14:30,904:INFO:Total runtime is 0.14726788997650145 minutes
2023-11-04 16:14:30,908:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:30,909:INFO:Initializing create_model()
2023-11-04 16:14:30,909:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:30,909:INFO:Checking exceptions
2023-11-04 16:14:30,909:INFO:Importing libraries
2023-11-04 16:14:30,909:INFO:Copying training dataset
2023-11-04 16:14:30,912:INFO:Defining folds
2023-11-04 16:14:30,912:INFO:Declaring metric variables
2023-11-04 16:14:30,915:INFO:Importing untrained model
2023-11-04 16:14:30,918:INFO:Light Gradient Boosting Machine Imported successfully
2023-11-04 16:14:30,924:INFO:Starting cross validation
2023-11-04 16:14:30,924:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:31,720:INFO:Calculating mean and std
2023-11-04 16:14:31,722:INFO:Creating metrics dataframe
2023-11-04 16:14:31,727:INFO:Uploading results into container
2023-11-04 16:14:31,728:INFO:Uploading model into container now
2023-11-04 16:14:31,728:INFO:_master_model_container: 13
2023-11-04 16:14:31,728:INFO:_display_container: 2
2023-11-04 16:14:31,729:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-11-04 16:14:31,729:INFO:create_model() successfully completed......................................
2023-11-04 16:14:31,847:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:31,848:INFO:Creating metrics dataframe
2023-11-04 16:14:31,857:INFO:Initializing Dummy Classifier
2023-11-04 16:14:31,857:INFO:Total runtime is 0.1631497224171956 minutes
2023-11-04 16:14:31,861:INFO:SubProcess create_model() called ==================================
2023-11-04 16:14:31,861:INFO:Initializing create_model()
2023-11-04 16:14:31,861:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C854FBE9E0>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:31,861:INFO:Checking exceptions
2023-11-04 16:14:31,861:INFO:Importing libraries
2023-11-04 16:14:31,861:INFO:Copying training dataset
2023-11-04 16:14:31,866:INFO:Defining folds
2023-11-04 16:14:31,866:INFO:Declaring metric variables
2023-11-04 16:14:31,869:INFO:Importing untrained model
2023-11-04 16:14:31,872:INFO:Dummy Classifier Imported successfully
2023-11-04 16:14:31,878:INFO:Starting cross validation
2023-11-04 16:14:31,878:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:14:31,909:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,910:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,911:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,913:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,914:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,915:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,916:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,919:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,919:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,921:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:14:31,925:INFO:Calculating mean and std
2023-11-04 16:14:31,926:INFO:Creating metrics dataframe
2023-11-04 16:14:31,928:INFO:Uploading results into container
2023-11-04 16:14:31,928:INFO:Uploading model into container now
2023-11-04 16:14:31,929:INFO:_master_model_container: 14
2023-11-04 16:14:31,929:INFO:_display_container: 2
2023-11-04 16:14:31,929:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-11-04 16:14:31,929:INFO:create_model() successfully completed......................................
2023-11-04 16:14:32,029:INFO:SubProcess create_model() end ==================================
2023-11-04 16:14:32,029:INFO:Creating metrics dataframe
2023-11-04 16:14:32,048:INFO:Initializing create_model()
2023-11-04 16:14:32,048:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=GaussianNB(priors=None, var_smoothing=1e-09), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:14:32,048:INFO:Checking exceptions
2023-11-04 16:14:32,049:INFO:Importing libraries
2023-11-04 16:14:32,050:INFO:Copying training dataset
2023-11-04 16:14:32,052:INFO:Defining folds
2023-11-04 16:14:32,052:INFO:Declaring metric variables
2023-11-04 16:14:32,052:INFO:Importing untrained model
2023-11-04 16:14:32,052:INFO:Declaring custom model
2023-11-04 16:14:32,052:INFO:Naive Bayes Imported successfully
2023-11-04 16:14:32,053:INFO:Cross validation set to False
2023-11-04 16:14:32,053:INFO:Fitting Model
2023-11-04 16:14:32,058:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-04 16:14:32,058:INFO:create_model() successfully completed......................................
2023-11-04 16:14:32,190:INFO:_master_model_container: 14
2023-11-04 16:14:32,191:INFO:_display_container: 2
2023-11-04 16:14:32,191:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-04 16:14:32,191:INFO:compare_models() successfully completed......................................
2023-11-04 16:14:32,192:INFO:Initializing evaluate_model()
2023-11-04 16:14:32,192:INFO:evaluate_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=GaussianNB(priors=None, var_smoothing=1e-09), fold=None, fit_kwargs=None, plot_kwargs=None, feature_name=None, groups=None)
2023-11-04 16:14:32,226:INFO:Initializing plot_model()
2023-11-04 16:14:32,226:INFO:plot_model(plot=pipeline, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), verbose=False, display=None, display_format=None, estimator=GaussianNB(priors=None, var_smoothing=1e-09), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, system=True)
2023-11-04 16:14:32,226:INFO:Checking exceptions
2023-11-04 16:14:32,228:INFO:Preloading libraries
2023-11-04 16:14:32,228:INFO:Copying training dataset
2023-11-04 16:14:32,228:INFO:Plot type: pipeline
2023-11-04 16:14:32,508:INFO:Visual Rendered Successfully
2023-11-04 16:14:32,607:INFO:plot_model() successfully completed......................................
2023-11-04 16:14:32,610:INFO:Initializing predict_model()
2023-11-04 16:14:32,610:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, estimator=GaussianNB(priors=None, var_smoothing=1e-09), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000002C85531E710>)
2023-11-04 16:14:32,610:INFO:Checking exceptions
2023-11-04 16:14:32,610:INFO:Preloading libraries
2023-11-04 16:14:32,612:INFO:Set up data.
2023-11-04 16:14:32,615:INFO:Set up index.
2023-11-04 16:14:32,748:INFO:Initializing save_model()
2023-11-04 16:14:32,748:INFO:save_model(model=GaussianNB(priors=None, var_smoothing=1e-09), model_name=my_best_pipeline_survived, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\HANNAH~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['sex', 'alone',
                                             'Siblings/spouses aboard',
                                             'Parents/children aboard',
                                             'Passenger fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              st...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2023-11-04 16:14:32,748:INFO:Adding model into prep_pipe
2023-11-04 16:14:32,751:INFO:my_best_pipeline_survived.pkl saved in current working directory
2023-11-04 16:14:32,755:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['sex', 'alone',
                                             'Siblings/spouses aboard',
                                             'Parents/children aboard',
                                             'Passenger fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('cat...
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 GaussianNB(priors=None, var_smoothing=1e-09))],
         verbose=False)
2023-11-04 16:14:32,755:INFO:save_model() successfully completed......................................
2023-11-04 16:14:35,522:INFO:Initializing plot_model()
2023-11-04 16:14:35,523:INFO:plot_model(plot=auc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), verbose=False, display=None, display_format=None, estimator=GaussianNB(priors=None, var_smoothing=1e-09), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, system=True)
2023-11-04 16:14:35,523:INFO:Checking exceptions
2023-11-04 16:14:35,525:INFO:Preloading libraries
2023-11-04 16:14:35,525:INFO:Copying training dataset
2023-11-04 16:14:35,525:INFO:Plot type: auc
2023-11-04 16:14:35,598:INFO:Fitting Model
2023-11-04 16:14:35,618:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

2023-11-04 16:14:35,618:INFO:Scoring test/hold-out set
2023-11-04 16:14:35,805:INFO:Visual Rendered Successfully
2023-11-04 16:14:35,922:INFO:plot_model() successfully completed......................................
2023-11-04 16:15:40,816:INFO:Initializing plot_model()
2023-11-04 16:15:40,816:INFO:plot_model(plot=confusion_matrix, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), verbose=False, display=None, display_format=None, estimator=GaussianNB(priors=None, var_smoothing=1e-09), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C81DF3BE20>, system=True)
2023-11-04 16:15:40,817:INFO:Checking exceptions
2023-11-04 16:15:40,819:INFO:Preloading libraries
2023-11-04 16:15:40,819:INFO:Copying training dataset
2023-11-04 16:15:40,820:INFO:Plot type: confusion_matrix
2023-11-04 16:15:40,871:INFO:Fitting Model
2023-11-04 16:15:40,871:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

2023-11-04 16:15:40,871:INFO:Scoring test/hold-out set
2023-11-04 16:15:40,966:INFO:Visual Rendered Successfully
2023-11-04 16:15:41,075:INFO:plot_model() successfully completed......................................
2023-11-04 16:16:25,270:INFO:PyCaret ClassificationExperiment
2023-11-04 16:16:25,270:INFO:Logging name: clf-default-name
2023-11-04 16:16:25,270:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-04 16:16:25,270:INFO:version 3.1.0
2023-11-04 16:16:25,270:INFO:Initializing setup()
2023-11-04 16:16:25,270:INFO:self.USI: d88e
2023-11-04 16:16:25,270:INFO:self._variable_keys: {'_ml_usecase', 'log_plots_param', 'is_multiclass', 'logging_param', 'fold_shuffle_param', 'gpu_n_jobs_param', 'target_param', 'X', 'X_test', 'memory', 'html_param', 'fold_groups_param', 'USI', 'exp_name_log', 'pipeline', 'data', 'fold_generator', 'seed', 'y_train', 'exp_id', 'X_train', 'fix_imbalance', 'idx', 'y_test', 'gpu_param', 'y', 'n_jobs_param', '_available_plots'}
2023-11-04 16:16:25,270:INFO:Checking environment
2023-11-04 16:16:25,271:INFO:python_version: 3.10.11
2023-11-04 16:16:25,271:INFO:python_build: ('tags/v3.10.11:7d4cc5a', 'Apr  5 2023 00:38:17')
2023-11-04 16:16:25,271:INFO:machine: AMD64
2023-11-04 16:16:25,271:INFO:platform: Windows-10-10.0.22621-SP0
2023-11-04 16:16:25,271:INFO:Memory: svmem(total=16542101504, available=2276171776, percent=86.2, used=14265929728, free=2276171776)
2023-11-04 16:16:25,271:INFO:Physical Core: 6
2023-11-04 16:16:25,271:INFO:Logical Core: 12
2023-11-04 16:16:25,271:INFO:Checking libraries
2023-11-04 16:16:25,271:INFO:System:
2023-11-04 16:16:25,271:INFO:    python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
2023-11-04 16:16:25,271:INFO:executable: C:\Users\Hannah Cimene\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
2023-11-04 16:16:25,271:INFO:   machine: Windows-10-10.0.22621-SP0
2023-11-04 16:16:25,271:INFO:PyCaret required dependencies:
2023-11-04 16:16:25,271:INFO:                 pip: 23.0.1
2023-11-04 16:16:25,271:INFO:          setuptools: 65.5.0
2023-11-04 16:16:25,271:INFO:             pycaret: 3.1.0
2023-11-04 16:16:25,271:INFO:             IPython: 8.15.0
2023-11-04 16:16:25,271:INFO:          ipywidgets: 8.1.1
2023-11-04 16:16:25,271:INFO:                tqdm: 4.64.1
2023-11-04 16:16:25,271:INFO:               numpy: 1.23.5
2023-11-04 16:16:25,271:INFO:              pandas: 1.5.2
2023-11-04 16:16:25,272:INFO:              jinja2: 3.1.2
2023-11-04 16:16:25,272:INFO:               scipy: 1.10.1
2023-11-04 16:16:25,272:INFO:              joblib: 1.2.0
2023-11-04 16:16:25,272:INFO:             sklearn: 1.2.2
2023-11-04 16:16:25,272:INFO:                pyod: 1.1.0
2023-11-04 16:16:25,272:INFO:            imblearn: 0.11.0
2023-11-04 16:16:25,272:INFO:   category_encoders: 2.6.2
2023-11-04 16:16:25,272:INFO:            lightgbm: 4.1.0
2023-11-04 16:16:25,272:INFO:               numba: 0.58.0
2023-11-04 16:16:25,272:INFO:            requests: 2.28.1
2023-11-04 16:16:25,272:INFO:          matplotlib: 3.6.3
2023-11-04 16:16:25,272:INFO:          scikitplot: 0.3.7
2023-11-04 16:16:25,272:INFO:         yellowbrick: 1.5
2023-11-04 16:16:25,272:INFO:              plotly: 5.17.0
2023-11-04 16:16:25,272:INFO:    plotly-resampler: Not installed
2023-11-04 16:16:25,272:INFO:             kaleido: 0.2.1
2023-11-04 16:16:25,272:INFO:           schemdraw: 0.15
2023-11-04 16:16:25,272:INFO:         statsmodels: 0.13.5
2023-11-04 16:16:25,272:INFO:              sktime: 0.21.1
2023-11-04 16:16:25,272:INFO:               tbats: 1.1.3
2023-11-04 16:16:25,272:INFO:            pmdarima: 2.0.3
2023-11-04 16:16:25,272:INFO:              psutil: 5.9.3
2023-11-04 16:16:25,272:INFO:          markupsafe: 2.1.1
2023-11-04 16:16:25,272:INFO:             pickle5: Not installed
2023-11-04 16:16:25,272:INFO:         cloudpickle: 2.2.1
2023-11-04 16:16:25,272:INFO:         deprecation: 2.1.0
2023-11-04 16:16:25,272:INFO:              xxhash: 3.3.0
2023-11-04 16:16:25,272:INFO:           wurlitzer: Not installed
2023-11-04 16:16:25,272:INFO:PyCaret optional dependencies:
2023-11-04 16:16:25,272:INFO:                shap: Not installed
2023-11-04 16:16:25,272:INFO:           interpret: Not installed
2023-11-04 16:16:25,272:INFO:                umap: Not installed
2023-11-04 16:16:25,272:INFO:     ydata_profiling: Not installed
2023-11-04 16:16:25,272:INFO:  explainerdashboard: Not installed
2023-11-04 16:16:25,272:INFO:             autoviz: Not installed
2023-11-04 16:16:25,272:INFO:           fairlearn: Not installed
2023-11-04 16:16:25,272:INFO:          deepchecks: Not installed
2023-11-04 16:16:25,272:INFO:             xgboost: Not installed
2023-11-04 16:16:25,272:INFO:            catboost: Not installed
2023-11-04 16:16:25,272:INFO:              kmodes: Not installed
2023-11-04 16:16:25,272:INFO:             mlxtend: Not installed
2023-11-04 16:16:25,272:INFO:       statsforecast: Not installed
2023-11-04 16:16:25,273:INFO:        tune_sklearn: Not installed
2023-11-04 16:16:25,273:INFO:                 ray: Not installed
2023-11-04 16:16:25,273:INFO:            hyperopt: Not installed
2023-11-04 16:16:25,273:INFO:              optuna: Not installed
2023-11-04 16:16:25,273:INFO:               skopt: Not installed
2023-11-04 16:16:25,273:INFO:              mlflow: Not installed
2023-11-04 16:16:25,273:INFO:              gradio: Not installed
2023-11-04 16:16:25,273:INFO:             fastapi: 0.87.0
2023-11-04 16:16:25,273:INFO:             uvicorn: 0.20.0
2023-11-04 16:16:25,273:INFO:              m2cgen: Not installed
2023-11-04 16:16:25,273:INFO:           evidently: Not installed
2023-11-04 16:16:25,273:INFO:               fugue: Not installed
2023-11-04 16:16:25,273:INFO:           streamlit: Not installed
2023-11-04 16:16:25,273:INFO:             prophet: Not installed
2023-11-04 16:16:25,273:INFO:None
2023-11-04 16:16:25,273:INFO:Set up data.
2023-11-04 16:16:25,278:INFO:Set up folding strategy.
2023-11-04 16:16:25,278:INFO:Set up train/test split.
2023-11-04 16:16:25,282:INFO:Set up index.
2023-11-04 16:16:25,282:INFO:Assigning column types.
2023-11-04 16:16:25,284:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-04 16:16:25,324:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-04 16:16:25,325:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:16:25,350:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,350:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,388:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-04 16:16:25,388:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:16:25,413:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,414:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,414:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-04 16:16:25,455:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:16:25,481:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,481:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,520:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-04 16:16:25,544:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,544:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,545:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-04 16:16:25,606:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,606:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,668:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,668:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,669:INFO:Preparing preprocessing pipeline...
2023-11-04 16:16:25,669:INFO:Set up simple imputation.
2023-11-04 16:16:25,670:INFO:Set up column name cleaning.
2023-11-04 16:16:25,687:INFO:Finished creating preprocessing pipeline.
2023-11-04 16:16:25,690:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\HANNAH~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['sex', 'alone',
                                             'Siblings/spouses aboard',
                                             'Parents/children aboard',
                                             'Passenger fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              st...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-11-04 16:16:25,690:INFO:Creating final display dataframe.
2023-11-04 16:16:25,746:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target          Survived
2                   Target type            Binary
3           Original data shape         (1309, 6)
4        Transformed data shape         (1309, 6)
5   Transformed train set shape          (916, 6)
6    Transformed test set shape          (393, 6)
7              Numeric features                 5
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              d88e
2023-11-04 16:16:25,815:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,816:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,890:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,890:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-11-04 16:16:25,890:INFO:setup() successfully completed in 0.62s...............
2023-11-04 16:16:25,890:INFO:Initializing compare_models()
2023-11-04 16:16:25,891:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-04 16:16:25,891:INFO:Checking exceptions
2023-11-04 16:16:25,893:INFO:Preparing display monitor
2023-11-04 16:16:25,917:INFO:Initializing Logistic Regression
2023-11-04 16:16:25,917:INFO:Total runtime is 0.0 minutes
2023-11-04 16:16:25,921:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:25,921:INFO:Initializing create_model()
2023-11-04 16:16:25,921:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:25,921:INFO:Checking exceptions
2023-11-04 16:16:25,921:INFO:Importing libraries
2023-11-04 16:16:25,921:INFO:Copying training dataset
2023-11-04 16:16:25,925:INFO:Defining folds
2023-11-04 16:16:25,925:INFO:Declaring metric variables
2023-11-04 16:16:25,929:INFO:Importing untrained model
2023-11-04 16:16:25,932:INFO:Logistic Regression Imported successfully
2023-11-04 16:16:25,939:INFO:Starting cross validation
2023-11-04 16:16:25,940:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:26,005:INFO:Calculating mean and std
2023-11-04 16:16:26,005:INFO:Creating metrics dataframe
2023-11-04 16:16:26,008:INFO:Uploading results into container
2023-11-04 16:16:26,008:INFO:Uploading model into container now
2023-11-04 16:16:26,008:INFO:_master_model_container: 1
2023-11-04 16:16:26,009:INFO:_display_container: 2
2023-11-04 16:16:26,009:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-11-04 16:16:26,009:INFO:create_model() successfully completed......................................
2023-11-04 16:16:26,113:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:26,113:INFO:Creating metrics dataframe
2023-11-04 16:16:26,120:INFO:Initializing K Neighbors Classifier
2023-11-04 16:16:26,120:INFO:Total runtime is 0.0033745129903157553 minutes
2023-11-04 16:16:26,123:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:26,123:INFO:Initializing create_model()
2023-11-04 16:16:26,123:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:26,123:INFO:Checking exceptions
2023-11-04 16:16:26,123:INFO:Importing libraries
2023-11-04 16:16:26,123:INFO:Copying training dataset
2023-11-04 16:16:26,126:INFO:Defining folds
2023-11-04 16:16:26,126:INFO:Declaring metric variables
2023-11-04 16:16:26,129:INFO:Importing untrained model
2023-11-04 16:16:26,132:INFO:K Neighbors Classifier Imported successfully
2023-11-04 16:16:26,137:INFO:Starting cross validation
2023-11-04 16:16:26,138:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:26,217:INFO:Calculating mean and std
2023-11-04 16:16:26,217:INFO:Creating metrics dataframe
2023-11-04 16:16:26,220:INFO:Uploading results into container
2023-11-04 16:16:26,220:INFO:Uploading model into container now
2023-11-04 16:16:26,220:INFO:_master_model_container: 2
2023-11-04 16:16:26,220:INFO:_display_container: 2
2023-11-04 16:16:26,221:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-11-04 16:16:26,221:INFO:create_model() successfully completed......................................
2023-11-04 16:16:26,330:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:26,330:INFO:Creating metrics dataframe
2023-11-04 16:16:26,339:INFO:Initializing Naive Bayes
2023-11-04 16:16:26,339:INFO:Total runtime is 0.0070179184277852375 minutes
2023-11-04 16:16:26,341:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:26,341:INFO:Initializing create_model()
2023-11-04 16:16:26,341:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:26,342:INFO:Checking exceptions
2023-11-04 16:16:26,342:INFO:Importing libraries
2023-11-04 16:16:26,342:INFO:Copying training dataset
2023-11-04 16:16:26,344:INFO:Defining folds
2023-11-04 16:16:26,344:INFO:Declaring metric variables
2023-11-04 16:16:26,348:INFO:Importing untrained model
2023-11-04 16:16:26,351:INFO:Naive Bayes Imported successfully
2023-11-04 16:16:26,356:INFO:Starting cross validation
2023-11-04 16:16:26,357:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:26,401:INFO:Calculating mean and std
2023-11-04 16:16:26,401:INFO:Creating metrics dataframe
2023-11-04 16:16:26,404:INFO:Uploading results into container
2023-11-04 16:16:26,404:INFO:Uploading model into container now
2023-11-04 16:16:26,404:INFO:_master_model_container: 3
2023-11-04 16:16:26,405:INFO:_display_container: 2
2023-11-04 16:16:26,405:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-04 16:16:26,405:INFO:create_model() successfully completed......................................
2023-11-04 16:16:26,506:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:26,506:INFO:Creating metrics dataframe
2023-11-04 16:16:26,515:INFO:Initializing Decision Tree Classifier
2023-11-04 16:16:26,515:INFO:Total runtime is 0.009957599639892577 minutes
2023-11-04 16:16:26,518:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:26,518:INFO:Initializing create_model()
2023-11-04 16:16:26,518:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:26,518:INFO:Checking exceptions
2023-11-04 16:16:26,518:INFO:Importing libraries
2023-11-04 16:16:26,518:INFO:Copying training dataset
2023-11-04 16:16:26,520:INFO:Defining folds
2023-11-04 16:16:26,520:INFO:Declaring metric variables
2023-11-04 16:16:26,523:INFO:Importing untrained model
2023-11-04 16:16:26,526:INFO:Decision Tree Classifier Imported successfully
2023-11-04 16:16:26,532:INFO:Starting cross validation
2023-11-04 16:16:26,533:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:26,581:INFO:Calculating mean and std
2023-11-04 16:16:26,581:INFO:Creating metrics dataframe
2023-11-04 16:16:26,584:INFO:Uploading results into container
2023-11-04 16:16:26,585:INFO:Uploading model into container now
2023-11-04 16:16:26,585:INFO:_master_model_container: 4
2023-11-04 16:16:26,585:INFO:_display_container: 2
2023-11-04 16:16:26,585:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-04 16:16:26,585:INFO:create_model() successfully completed......................................
2023-11-04 16:16:26,697:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:26,697:INFO:Creating metrics dataframe
2023-11-04 16:16:26,707:INFO:Initializing SVM - Linear Kernel
2023-11-04 16:16:26,707:INFO:Total runtime is 0.013160185019175211 minutes
2023-11-04 16:16:26,710:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:26,710:INFO:Initializing create_model()
2023-11-04 16:16:26,710:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:26,710:INFO:Checking exceptions
2023-11-04 16:16:26,710:INFO:Importing libraries
2023-11-04 16:16:26,710:INFO:Copying training dataset
2023-11-04 16:16:26,714:INFO:Defining folds
2023-11-04 16:16:26,714:INFO:Declaring metric variables
2023-11-04 16:16:26,717:INFO:Importing untrained model
2023-11-04 16:16:26,720:INFO:SVM - Linear Kernel Imported successfully
2023-11-04 16:16:26,726:INFO:Starting cross validation
2023-11-04 16:16:26,728:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:26,757:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,760:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,760:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,762:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,763:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,764:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:16:26,764:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,765:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,765:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,768:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-11-04 16:16:26,769:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,771:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-04 16:16:26,778:INFO:Calculating mean and std
2023-11-04 16:16:26,778:INFO:Creating metrics dataframe
2023-11-04 16:16:26,781:INFO:Uploading results into container
2023-11-04 16:16:26,782:INFO:Uploading model into container now
2023-11-04 16:16:26,782:INFO:_master_model_container: 5
2023-11-04 16:16:26,782:INFO:_display_container: 2
2023-11-04 16:16:26,783:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-04 16:16:26,783:INFO:create_model() successfully completed......................................
2023-11-04 16:16:26,896:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:26,896:INFO:Creating metrics dataframe
2023-11-04 16:16:26,905:INFO:Initializing Ridge Classifier
2023-11-04 16:16:26,905:INFO:Total runtime is 0.016463470458984376 minutes
2023-11-04 16:16:26,907:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:26,909:INFO:Initializing create_model()
2023-11-04 16:16:26,909:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:26,909:INFO:Checking exceptions
2023-11-04 16:16:26,909:INFO:Importing libraries
2023-11-04 16:16:26,909:INFO:Copying training dataset
2023-11-04 16:16:26,913:INFO:Defining folds
2023-11-04 16:16:26,913:INFO:Declaring metric variables
2023-11-04 16:16:26,916:INFO:Importing untrained model
2023-11-04 16:16:26,919:INFO:Ridge Classifier Imported successfully
2023-11-04 16:16:26,925:INFO:Starting cross validation
2023-11-04 16:16:26,926:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:26,955:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,956:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,957:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,958:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,960:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,962:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,962:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,962:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,963:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,968:WARNING:C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Hannah Cimene\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-04 16:16:26,976:INFO:Calculating mean and std
2023-11-04 16:16:26,977:INFO:Creating metrics dataframe
2023-11-04 16:16:26,981:INFO:Uploading results into container
2023-11-04 16:16:26,981:INFO:Uploading model into container now
2023-11-04 16:16:26,982:INFO:_master_model_container: 6
2023-11-04 16:16:26,982:INFO:_display_container: 2
2023-11-04 16:16:26,983:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-04 16:16:26,983:INFO:create_model() successfully completed......................................
2023-11-04 16:16:27,119:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:27,121:INFO:Creating metrics dataframe
2023-11-04 16:16:27,131:INFO:Initializing Random Forest Classifier
2023-11-04 16:16:27,131:INFO:Total runtime is 0.02023300329844157 minutes
2023-11-04 16:16:27,135:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:27,135:INFO:Initializing create_model()
2023-11-04 16:16:27,135:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:27,135:INFO:Checking exceptions
2023-11-04 16:16:27,135:INFO:Importing libraries
2023-11-04 16:16:27,135:INFO:Copying training dataset
2023-11-04 16:16:27,140:INFO:Defining folds
2023-11-04 16:16:27,140:INFO:Declaring metric variables
2023-11-04 16:16:27,143:INFO:Importing untrained model
2023-11-04 16:16:27,146:INFO:Random Forest Classifier Imported successfully
2023-11-04 16:16:27,152:INFO:Starting cross validation
2023-11-04 16:16:27,154:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:27,485:INFO:Calculating mean and std
2023-11-04 16:16:27,487:INFO:Creating metrics dataframe
2023-11-04 16:16:27,491:INFO:Uploading results into container
2023-11-04 16:16:27,492:INFO:Uploading model into container now
2023-11-04 16:16:27,492:INFO:_master_model_container: 7
2023-11-04 16:16:27,492:INFO:_display_container: 2
2023-11-04 16:16:27,493:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-11-04 16:16:27,493:INFO:create_model() successfully completed......................................
2023-11-04 16:16:27,600:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:27,601:INFO:Creating metrics dataframe
2023-11-04 16:16:27,610:INFO:Initializing Quadratic Discriminant Analysis
2023-11-04 16:16:27,610:INFO:Total runtime is 0.028205883502960206 minutes
2023-11-04 16:16:27,613:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:27,613:INFO:Initializing create_model()
2023-11-04 16:16:27,613:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:27,613:INFO:Checking exceptions
2023-11-04 16:16:27,613:INFO:Importing libraries
2023-11-04 16:16:27,613:INFO:Copying training dataset
2023-11-04 16:16:27,617:INFO:Defining folds
2023-11-04 16:16:27,617:INFO:Declaring metric variables
2023-11-04 16:16:27,620:INFO:Importing untrained model
2023-11-04 16:16:27,623:INFO:Quadratic Discriminant Analysis Imported successfully
2023-11-04 16:16:27,629:INFO:Starting cross validation
2023-11-04 16:16:27,630:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:27,687:INFO:Calculating mean and std
2023-11-04 16:16:27,688:INFO:Creating metrics dataframe
2023-11-04 16:16:27,692:INFO:Uploading results into container
2023-11-04 16:16:27,693:INFO:Uploading model into container now
2023-11-04 16:16:27,694:INFO:_master_model_container: 8
2023-11-04 16:16:27,694:INFO:_display_container: 2
2023-11-04 16:16:27,694:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-11-04 16:16:27,694:INFO:create_model() successfully completed......................................
2023-11-04 16:16:27,805:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:27,805:INFO:Creating metrics dataframe
2023-11-04 16:16:27,814:INFO:Initializing Ada Boost Classifier
2023-11-04 16:16:27,815:INFO:Total runtime is 0.031620347499847413 minutes
2023-11-04 16:16:27,818:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:27,818:INFO:Initializing create_model()
2023-11-04 16:16:27,818:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:27,818:INFO:Checking exceptions
2023-11-04 16:16:27,819:INFO:Importing libraries
2023-11-04 16:16:27,819:INFO:Copying training dataset
2023-11-04 16:16:27,823:INFO:Defining folds
2023-11-04 16:16:27,823:INFO:Declaring metric variables
2023-11-04 16:16:27,825:INFO:Importing untrained model
2023-11-04 16:16:27,828:INFO:Ada Boost Classifier Imported successfully
2023-11-04 16:16:27,835:INFO:Starting cross validation
2023-11-04 16:16:27,836:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:27,989:INFO:Calculating mean and std
2023-11-04 16:16:27,991:INFO:Creating metrics dataframe
2023-11-04 16:16:27,994:INFO:Uploading results into container
2023-11-04 16:16:27,994:INFO:Uploading model into container now
2023-11-04 16:16:27,995:INFO:_master_model_container: 9
2023-11-04 16:16:27,995:INFO:_display_container: 2
2023-11-04 16:16:27,995:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-11-04 16:16:27,995:INFO:create_model() successfully completed......................................
2023-11-04 16:16:28,098:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:28,098:INFO:Creating metrics dataframe
2023-11-04 16:16:28,107:INFO:Initializing Gradient Boosting Classifier
2023-11-04 16:16:28,107:INFO:Total runtime is 0.0364996353785197 minutes
2023-11-04 16:16:28,111:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:28,111:INFO:Initializing create_model()
2023-11-04 16:16:28,111:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:28,111:INFO:Checking exceptions
2023-11-04 16:16:28,111:INFO:Importing libraries
2023-11-04 16:16:28,111:INFO:Copying training dataset
2023-11-04 16:16:28,116:INFO:Defining folds
2023-11-04 16:16:28,116:INFO:Declaring metric variables
2023-11-04 16:16:28,119:INFO:Importing untrained model
2023-11-04 16:16:28,122:INFO:Gradient Boosting Classifier Imported successfully
2023-11-04 16:16:28,127:INFO:Starting cross validation
2023-11-04 16:16:28,129:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:28,292:INFO:Calculating mean and std
2023-11-04 16:16:28,293:INFO:Creating metrics dataframe
2023-11-04 16:16:28,296:INFO:Uploading results into container
2023-11-04 16:16:28,296:INFO:Uploading model into container now
2023-11-04 16:16:28,297:INFO:_master_model_container: 10
2023-11-04 16:16:28,297:INFO:_display_container: 2
2023-11-04 16:16:28,297:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-11-04 16:16:28,297:INFO:create_model() successfully completed......................................
2023-11-04 16:16:28,402:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:28,403:INFO:Creating metrics dataframe
2023-11-04 16:16:28,412:INFO:Initializing Linear Discriminant Analysis
2023-11-04 16:16:28,412:INFO:Total runtime is 0.04157106876373291 minutes
2023-11-04 16:16:28,416:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:28,416:INFO:Initializing create_model()
2023-11-04 16:16:28,417:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:28,417:INFO:Checking exceptions
2023-11-04 16:16:28,417:INFO:Importing libraries
2023-11-04 16:16:28,417:INFO:Copying training dataset
2023-11-04 16:16:28,421:INFO:Defining folds
2023-11-04 16:16:28,421:INFO:Declaring metric variables
2023-11-04 16:16:28,424:INFO:Importing untrained model
2023-11-04 16:16:28,427:INFO:Linear Discriminant Analysis Imported successfully
2023-11-04 16:16:28,433:INFO:Starting cross validation
2023-11-04 16:16:28,434:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:28,480:INFO:Calculating mean and std
2023-11-04 16:16:28,482:INFO:Creating metrics dataframe
2023-11-04 16:16:28,484:INFO:Uploading results into container
2023-11-04 16:16:28,485:INFO:Uploading model into container now
2023-11-04 16:16:28,485:INFO:_master_model_container: 11
2023-11-04 16:16:28,485:INFO:_display_container: 2
2023-11-04 16:16:28,485:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-11-04 16:16:28,485:INFO:create_model() successfully completed......................................
2023-11-04 16:16:28,587:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:28,587:INFO:Creating metrics dataframe
2023-11-04 16:16:28,597:INFO:Initializing Extra Trees Classifier
2023-11-04 16:16:28,597:INFO:Total runtime is 0.044652732213338216 minutes
2023-11-04 16:16:28,600:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:28,600:INFO:Initializing create_model()
2023-11-04 16:16:28,600:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:28,600:INFO:Checking exceptions
2023-11-04 16:16:28,600:INFO:Importing libraries
2023-11-04 16:16:28,600:INFO:Copying training dataset
2023-11-04 16:16:28,604:INFO:Defining folds
2023-11-04 16:16:28,604:INFO:Declaring metric variables
2023-11-04 16:16:28,606:INFO:Importing untrained model
2023-11-04 16:16:28,610:INFO:Extra Trees Classifier Imported successfully
2023-11-04 16:16:28,616:INFO:Starting cross validation
2023-11-04 16:16:28,616:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-04 16:16:28,979:INFO:Calculating mean and std
2023-11-04 16:16:28,981:INFO:Creating metrics dataframe
2023-11-04 16:16:28,984:INFO:Uploading results into container
2023-11-04 16:16:28,985:INFO:Uploading model into container now
2023-11-04 16:16:28,985:INFO:_master_model_container: 12
2023-11-04 16:16:28,985:INFO:_display_container: 2
2023-11-04 16:16:28,986:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-11-04 16:16:28,986:INFO:create_model() successfully completed......................................
2023-11-04 16:16:29,088:INFO:SubProcess create_model() end ==================================
2023-11-04 16:16:29,088:INFO:Creating metrics dataframe
2023-11-04 16:16:29,098:INFO:Initializing Light Gradient Boosting Machine
2023-11-04 16:16:29,098:INFO:Total runtime is 0.0530076543490092 minutes
2023-11-04 16:16:29,101:INFO:SubProcess create_model() called ==================================
2023-11-04 16:16:29,102:INFO:Initializing create_model()
2023-11-04 16:16:29,102:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000002C854F48100>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002C855831660>, model_only=True, return_train_score=False, kwargs={})
2023-11-04 16:16:29,102:INFO:Checking exceptions
2023-11-04 16:16:29,102:INFO:Importing libraries
2023-11-04 16:16:29,102:INFO:Copying training dataset
2023-11-04 16:16:29,106:INFO:Defining folds
2023-11-04 16:16:29,107:INFO:Declaring metric variables
2023-11-04 16:16:29,110:INFO:Importing untrained model
2023-11-04 16:16:29,114:INFO:Light Gradient Boosting Machine Imported successfully
2023-11-04 16:16:29,121:INFO:Starting cross validation
2023-11-04 16:16:29,122:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
